eureka:
  client:
  #  registerWithEureka: true  #是否注册自身到eureka服务器
  #  fetchRegistry: true  #fetchRegistry表示是否从eureka服务器获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign.hystrix.enabled: true
server:
  port: 8765
spring:
  application:
    name: eureka-client-feign