spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    port: 5672
    host: 172.16.136.138
    username: guest
    password: guest
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
