eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      #url: http://localhost:8762
      #serviceId: hiapi-vl
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: service-ribbon
    feignapi:
      path: /feignapi/**
      serviceId: eureka-client-feign
  #prefix: /vl
#ribbon:
  #eureka:
   # enabled: false
#hiapi-vl:
  #ribbon:
   # listOfServers: http://localhost:8763,http://localhost:8762